idf_component_register(INCLUDE_DIRS "./" SRCS
    "app/bitmaps.cpp"
    "app/ui.cpp"
    "display/screen.cpp"
    "display/touch.cpp"
    "drivers/gpio_interrupt.cpp"
    "drivers/gpio_pin.cpp"
    "drivers/gpio_pwm.cpp"
    "drivers/nvs_storage.cpp"
    "drivers/spi_bus.cpp"
    "drivers/spi_device.cpp"
    "fonts/ecam_value_14.cpp"
    "fonts/ecam_value_16.cpp"
    "graphics/bitmaps.cpp"
    "graphics/gauges.cpp"
    "graphics/shapes.cpp"
    "main/main.cpp"
)
